export const ALL_HEADER_REQUEST = "ALL_HEADER_REQUEST";
export const ALL_HEADER_SUCCESS = "ALL_HEADER_SUCCESS";
export const ALL_HEADER_FAIL = "ALL_HEADER_FAIL";

export const HEADER_DETAILS_REQUEST = "HEADER_DETAILS_REQUEST";
export const HEADER_DETAILS_SUCCESS = "HEADER_DETAILS_SUCCESS";
export const HEADER_DETAILS_FAIL = "HEADER_DETAILS_FAIL";

export const NEW_HEADER_REQUEST = "NEW_HEADER_REQUEST";
export const NEW_HEADER_SUCCESS = "NEW_HEADER_SUCCESS";
export const NEW_HEADER_RESET = "NEW_HEADER_RESET";
export const NEW_HEADER_FAIL = "NEW_HEADER_FAIL";

export const ADMIN_HEADER_REQUEST = "ADMIN_HEADER_REQUEST";
export const ADMIN_HEADER_SUCCESS = "ADMIN_HEADER_SUCCESS";
export const ADMIN_HEADER_FAIL = "ADMIN_HEADER_FAIL";

export const DELETE_HEADER_REQUEST = "DELETE_HEADER_REQUEST";
export const DELETE_HEADER_SUCCESS = "DELETE_HEADER_SUCCESS";
export const DELETE_HEADER_RESET = "DELETE_HEADER_RESET";
export const DELETE_HEADER_FAIL = "DELETE_HEADER_FAIL";

export const UPDATE_HEADER_REQUEST = "UPDATE_HEADER_REQUEST";
export const UPDATE_HEADER_SUCCESS = "UPDATE_HEADER_SUCCESS";
export const UPDATE_HEADER_FAIL = "UPDATE_HEADER_FAIL";
export const UPDATE_HEADER_RESET = "UPDATE_HEADER_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";